In [13]:
import pandas as pd
dir = 'Dataset/Events2Text'

In [14]:
df_dataset = pd.read_json(f'{dir}/player2vec_dataset.json')
df_dataset.head()

,season,playerId,playerName,teamId,teamName,text,match
0,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Tackle da centrocampo, fascia destra (tackle...",2019-08-12_Man Utd_Chelsea
1,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da centrocampo, fascia destra a cen...",2019-08-20_Wolves_Man Utd
2,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da trequarti difensiva, centro dest...",2019-08-26_Man Utd_Crystal Palace
3,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da trequarti difensiva, centro dest...",2019-09-01_Southampton_Man Utd
4,2019-2020,100008,Victor Lindelöf,32,Man Utd,"Passaggio da centrocampo, centrale a centroca...",2019-09-15_Man Utd_Leicester

In [15]:
player_season_counts = df_dataset.groupby(['playerId', 'playerName', 'season']).size().reset_index(name='row_count')
print(len(player_season_counts))
player_season_counts.head()

22307

   playerId         playerName     season  row_count
0       217    Claudio Pizarro  2019-2020         18
1      2794  Souleymane Camara  2019-2020         13
2      2837      Jermain Defoe  2019-2020          1
3      2943   Christian Maggio  2020-2021          8
4      2987         Pepe Reina  2019-2020         14

In [39]:
#player_season_counts[[player_season_counts.playerId == 349207.0] and [player_season_counts.season == '2021-2022']]['row_count']
p = player_season_counts[(player_season_counts['playerId'] == 349207.0) & (player_season_counts['season'] == '2021-2022')]['row_count']
int(p.loc[p.index[0]])

38

In [16]:
vocab = getTotalVocab()
df_dataset['text'][0]

'Tackle  da centrocampo, fascia destra  (tackle perso). Spazzata  da difesa, centrale a trequarti difensiva, fascia sinistra  (spazzata efficace, spazzata effettuata di testa, colpo di testa). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, centro destra a difesa, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da centrocampo, centro sinistra a centrocampo, centro sinistra  (preciso in avanti, preciso, corto preciso, di testa, in avanti, verso destra, passaggio di testa). Passaggio  da difesa, centro destra a difesa, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia sinistra  (retropassaggio impreciso, impreciso, pallonetto/passaggio alto, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, fascia destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, fascia sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro sinistra  (preciso, lancio lungo preciso, retropassaggio, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro sinistra a difesa, centrale  (preciso, lancio lungo preciso, retropassaggio, verso destra, lancio lungo). Passaggio  da difesa, centrale a difesa, centrale  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, lancio lungo preciso, in avanti, verso destra, lancio lungo). Recupero possesso  da trequarti difensiva, fascia destra, Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, corto impreciso, in avanti, verso sinistra). Passaggio  da centrocampo, centrale a centrocampo, fascia destra  (preciso, corto preciso, in avanti, verso destra). Recupero possesso  da trequarti difensiva, centro destra, Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, centro destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Dribbling  da trequarti difensiva, centro sinistra  (dribbling riuscito), Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, centro destra a difesa, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da difesa, fascia destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da centrocampo, fascia destra a centrocampo, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da difesa, centro destra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio bloccato  da centrocampo, centro destra  (passaggio bloccato da un giocatore di movimento). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso sinistra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, fascia destra  (preciso, corto preciso, retropassaggio, verso destra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso sinistra). Recupero possesso  da difesa, centro destra, Passaggio  da difesa, centro destra a centrocampo, centro destra  (impreciso, lancio lungo impreciso, in avanti, verso destra, lancio lungo). Contesa pallone in aria  da difesa, centrale  (duello aereo perso, duello difensivo). Passaggio  da difesa, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, centro destra a difesa, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da difesa, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Recupero possesso  da trequarti difensiva, fascia destra, Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Contesa pallone in aria  da centrocampo, centro sinistra  (duello aereo vinto, duello difensivo), Passaggio  da centrocampo, centro sinistra a centrocampo, fascia sinistra  (impreciso, corto impreciso, di testa, in avanti, verso sinistra, passaggio di testa). Passaggio  da trequarti offensiva, fascia sinistra a trequarti offensiva, fascia sinistra  (impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro sinistra a centrocampo, centro destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso destra, lancio lungo). Spazzata  da difesa, centrale a trequarti difensiva, centro destra  (spazzata efficace, spazzata effettuata di testa, colpo di testa). Intercettazione  da trequarti difensiva, centrale  (intercettazione riuscita). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, preciso da punizione, in avanti, verso sinistra, calcio di punizione battuto). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da difesa, fascia destra a trequarti difensiva, centro destra  (retropassaggio impreciso, impreciso, lancio lungo impreciso, in avanti, verso sinistra, lancio lungo). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Sanzione   (ammonizione). Contesa pallone in aria  da difesa, centrale  (duello aereo perso, duello difensivo). Passaggio  da difesa, centro destra a trequarti difensiva, centro destra  (preciso, pallonetto/passaggio alto, lancio lungo preciso, in avanti, lancio lungo). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centro destra a centrocampo, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, fascia destra  (preciso in avanti, preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, centrale  (preciso, corto preciso, in avanti, verso destra). Tocco palla  da trequarti difensiva, centro destra. Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, centro destra  (retropassaggio impreciso, impreciso, corto impreciso, verso sinistra). Passaggio  da centrocampo, fascia destra a centrocampo, fascia destra  (retropassaggio impreciso, impreciso, corto impreciso, in avanti, verso destra, azione offensiva). Passaggio  da trequarti difensiva, fascia destra a trequarti difensiva, fascia destra  (preciso, corto preciso, in avanti, verso sinistra). Spazzata  da difesa, centro destra a trequarti difensiva, centro sinistra  (spazzata efficace). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centro destra  (preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, fascia destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Passaggio  da centrocampo, centro destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Salvataggio  da difesa, centro destra  (blocco effettuato da un giocatore di movimento, blocco effettuato da un giocatore di movimento). Passaggio  da centrocampo, centrale a centrocampo, centro destra  (preciso, corto preciso, in avanti, verso destra). Passaggio  da centrocampo, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centro destra a centrocampo, centro destra  (preciso in avanti, preciso, corto preciso, in avanti, verso sinistra). Passaggio  da trequarti difensiva, centro destra a trequarti difensiva, centrale  (preciso, corto preciso, retropassaggio, verso sinistra). Passaggio  da trequarti difensiva, centrale a trequarti difensiva, fascia destra  (preciso, corto preciso, retropassaggio, verso destra). Recupero possesso  da trequarti difensiva, centro sinistra, Passaggio  da trequarti difensiva, centro sinistra a trequarti difensiva, centro sinistra  (preciso, corto preciso, in avanti, verso sinistra)'

In [3]:
import os
s = 'Europa-Champions-League_2023-2024_teams'
for s in os.listdir('Dataset/Events2Text/TeamPlayerList'):
    print(s.split('_')[1])

2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024
2019-2020
2020-2021
2021-2022
2022-2023
2023-2024

In [ ]:
import utils
def getTeamsPlayerDict(path: str) -> set:
    team_list = {}
    #for file in os.listdir(path):
    for file in os.listdir(path):
        nazione = file.split('-')[0]
        season = file.split('_')[1]
        if season not in team_list.keys():
            team_list[season] = {}

        dict_file = utils.readJson(f'{path}/{file}')

        for k, v in dict_file.items():
            if nazione != 'Europa':
                team_list[season][k] = v


    return team_list

getTeamDict('Dataset/Events2Text/TeamPlayerList')['2021-2022']['80']

{'name': 'AC Milan',
 'players': {'141646.0': 'Mike Maignan',
  '343501.0': 'Sandro Tonali',
  '294163.0': 'Rade Krunic',
  '303115.0': 'Theo Hernández',
  '24444.0': 'Olivier Giroud',
  '317507.0': 'Fikayo Tomori',
  '20769.0': 'Simon Kjær',
  '365308.0': 'Alexis Saelemaekers',
  '349207.0': 'Rafael Leão',
  '260498.0': 'Davide Calabria',
  '317541.0': 'Brahim Díaz',
  '101735.0': 'Ante Rebic',
  '259102.0': 'Ismaël Bennacer',
  '101596.0': 'Alessandro Florenzi',
  '118158.0': 'Alessio Romagnoli',
  '388493.0': 'Daniel Maldini',
  '238773.0': 'Samu Castillejo',
  '277269.0': 'Franck Kessie',
  '3281.0': 'Zlatan Ibrahimovic',
  '135211.0': 'Tiémoué Bakayoko',
  '328968.0': 'Fodé Ballo-Touré',
  '391836.0': 'Pierre Kalulu',
  '337443.0': 'Matteo Gabbia',
  '332270.0': 'Pietro Pellegri',
  '401098.0': 'Junior Messias',
  '32676.0': 'Ciprian Tatarusanu',
  '294137.0': 'Andrea Conti',
  '411943.0': 'Luca Stanga'}}

In [ ]:
lista_1 = ["tiro fuori bersaglio dall'interno dell'area attacco, centro sinistra", "tiro fuori bersaglio dall'interno dell'area attacco, centro destra", "tiro dall'area di rigore attacco, centro sinistra", "parata fuori dall'area di rigore attacco, centro sinistra", "tiro dall'area di rigore attacco, centro destra", "parata fuori dall'area di rigore attacco, centro destra", 'perde il controllo del pallone correndo attacco, centro sinistra', "tiro dall'area piccola attacco, centro sinistra", 'parata su tiro fuori area attacco, centro sinistra', 'parata su tiro fuori area attacco, centro destra', 'perde il controllo del pallone correndo attacco, centro destra', 'tiro bloccato attacco, centro sinistra', "tiro dall'area piccola attacco, centro destra", "parata nell'area di rigore attacco, centro sinistra", 'perde il controllo del pallone attacco, centro sinistra', "tiro fuori bersaglio dall'interno dell'area attacco, centrale", 'rigore sbagliato attacco, centro destra', 'rigore sbagliato attacco, centro sinistra', 'perde il controllo del pallone attacco, centro destra', "blocco nell'area piccola attacco, centro sinistra"]
lista_2 = ["tiro fuori bersaglio dall'interno dell'area attacco, centro sinistra", "tiro fuori bersaglio dall'interno dell'area attacco, centro destra", "tiro dall'area di rigore attacco, centro sinistra", "parata fuori dall'area di rigore attacco, centro sinistra", "tiro dall'area di rigore attacco, centro destra", "parata fuori dall'area di rigore attacco, centro destra", "tiro dall'area piccola attacco, centro sinistra", 'azione eseguita con una parte del corpo diversa attacco, centro sinistra', 'parata su tiro fuori area attacco, centro sinistra', 'azione offensiva attacco, centro sinistra', 'azione di contropiede attacco, centro sinistra', 'parata su tiro fuori area attacco, centro destra', 'tiro bloccato attacco, centro sinistra', 'azione offensiva attacco, centro destra', 'azione eseguita con i piedi attacco, centro sinistra', "tiro dall'area piccola attacco, centro destra", "parata nell'area di rigore attacco, centro sinistra", 'azione bloccata attacco, centro sinistra', 'azione di contropiede attacco, centro destra', "tiro fuori bersaglio dall'interno dell'area attacco, centrale"]
k = 0
for i,j in zip(lista_1, lista_2):
    if i != j:
        k+=1
        print(f'{i} ---{j}')

k

perde il controllo del pallone correndo attacco, centro sinistra ---tiro dall'area piccola attacco, centro sinistra
tiro dall'area piccola attacco, centro sinistra ---azione eseguita con una parte del corpo diversa attacco, centro sinistra
parata su tiro fuori area attacco, centro destra ---azione offensiva attacco, centro sinistra
perde il controllo del pallone correndo attacco, centro destra ---azione di contropiede attacco, centro sinistra
tiro bloccato attacco, centro sinistra ---parata su tiro fuori area attacco, centro destra
tiro dall'area piccola attacco, centro destra ---tiro bloccato attacco, centro sinistra
parata nell'area di rigore attacco, centro sinistra ---azione offensiva attacco, centro destra
perde il controllo del pallone attacco, centro sinistra ---azione eseguita con i piedi attacco, centro sinistra
tiro fuori bersaglio dall'interno dell'area attacco, centrale ---tiro dall'area piccola attacco, centro destra
rigore sbagliato attacco, centro destra ---parata nell'area di rigore attacco, centro sinistra
rigore sbagliato attacco, centro sinistra ---azione bloccata attacco, centro sinistra
perde il controllo del pallone attacco, centro destra ---azione di contropiede attacco, centro destra
blocco nell'area piccola attacco, centro sinistra ---tiro fuori bersaglio dall'interno dell'area attacco, centrale

13

: